name: pydui
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=22.2.2
  - python=3.9.13
  - black=22.6.0
  - sphinx=5.1.1
  - pip:
    - gobject==0.1.0
    - pycairo==1.21.0
    - pygobject==3.42.2
    - sphinx-rtd-theme==1.0.0
    - myst_parser==0.18.0
    - recommonmark==0.7.1
