name: pydui
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=22.2.2
  - python=3.9
  - black=22.6.0
  - pip:
    - pynoticenter
    - poga
    - PyGObject-stubs
    - pycairo = ">=1.21.0"
    - pygobject = ">=3.42.2"
