name: pydui
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=22.2.2
  - python=3.9
  - black=22.6.0
  - sphinx=5.1.1
  - pathlib=1.0.1
  - pip:
    - gobject==0.1.0
    - pycairo==1.21.0
    - pygobject==3.42.2
    - asyncio==3.4.3
    - pynoticenter>=0.1.8
    - poga>=0.1.10
    - myst_parser==0.18.0
    - recommonmark==0.7.1
    - sphinx-intl==2.0.1
    - piccolo-theme==0.12.0
    - meson==0.63.2
    - ninja==1.10.2.3
